name: civic_works_app
description: A new Flutter project for Civic Works.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  intl: ^0.18.0
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  font_awesome_flutter: ^10.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
