services:
  civic-mysql:
    image: mysql:8.0
    container_name: civic_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: civic_works_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  civic-redis:
    image: redis:7.0-alpine
    container_name: civic_redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
